export const ADD_ROOM = 'ADD_ROOM';
export const REMOVE_ROOM = 'REMOVE_ROOM';
export const EDIT_ROOM = 'EDIT_ROOM';
export const SELECT_ROOM = 'SELECT_ROOM';
export const UPDATE_ROOM_NAME = 'UPDATE_ROOM_NAME';
export const UPDATE_LOCATION_NAME = 'UPDATE_LOCATION_NAME';


export const ADD_CHEMICAL = 'ADD_CHEMICAL';
export const REMOVE_CHEMICAL = 'REMOVE_CHEMICAL';
export const EDIT_CHEMICAL = 'EDIT_CHEMICAL';
export const SELECT_CHEMICAL = 'SELECT_CHEMICAL';
export const UPDATE_CHEMICAL_NAME = 'UPDATE_CHEMICAL_NAME';
export const UPDATE_CHEMICAL_TRADE_NAME = 'UPDATE_CHEMICAL_TRADE_NAME';
export const UPDATE_CHEMICAL_QUANTITY = 'UPDATE_CHEMICAL_QUANTITY';
export const UPDATE_CHEMICAL_UOM = 'UPDATE_CHEMICAL_UOM';
export const UPDATE_CABINET_NAME = 'UPDATE_CABINET_NAME';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';